language: php
php:
  - '5.5'
  - '5.6'
  - '7'
  - 'hhvm'
matrix:
  allow_failures:
  - php: '7'
  - php: 'hhvm'
before_script:
  - travis_retry composer self-update
  - travis_retry composer install --no-interaction --prefer-source --dev
script:
  - bin/phpunit
