#!/usr/bin/env php
<?php

namespace Sysdiag\Console;

require __DIR__.'/vendor/autoload.php';

use Sysdiag\Application\Application;
use Sysdiag\Command\DiagnosisCommand;

$application = new Application('Sysdiag', '1.0');

$application->add(new DiagnosisCommand());

$application->run();
